# Don't insert a blank line between prompts
add_newline = false

format = """
$directory
$character
"""

[directory]
style = "bold #CE7688"
format = "╭─╼ [$path]($style) "
truncate_to_repo = false
truncation_length = 0

[character]
success_symbol = "[╰─❮](bold #CE7688) "
error_symbol   = "[╰─❮](bold #A05969) "
vimcmd_symbol  = "[╰─❮](bold #968C6E) "

[git_branch]
symbol = " "
style = "#965363"

[git_status]
style = "#A05969"

[hostname]
disabled = true

[username]
disabled = true

[time]
disabled = true
